<div class='row'>
	<div class='col-sm-3 hidden-phone'>
		<img src='http://placehold.it/300&text=Generic+Image'>
	</div>
	<div class='col-sm-9'>
		<p>Bacon ipsum dolor sit amet aliquip pork belly cupidatat occaecat laboris. Est biltong drumstick ex. Deserunt pancetta ut, kevin mollit corned beef shank. Ground round aute jerky turkey boudin jowl. Ad swine elit ball tip, turkey culpa brisket veniam voluptate spare ribs short loin. Nisi laborum commodo pastrami leberkas ullamco consectetur flank fatback. Tempor drumstick reprehenderit ribeye ground round.</p>
		<p>Prosciutto irure et capicola dolor ribeye. Pancetta aute kielbasa bacon qui sunt. Pariatur consectetur sunt sed kevin non. Incididunt ut officia brisket veniam pig shoulder kevin in pork belly.</p>
		<p>Pork loin deserunt jowl shank jerky. Pancetta minim proident, shoulder cow andouille duis labore id t-bone biltong shank. Dolore bresaola beef ribs ea nisi ut non hamburger quis. Swine doner ad pariatur, dolor chuck tenderloin leberkas.</p>
		<p>Dolore do occaecat cillum, qui incididunt flank. Laboris dolore nostrud, beef ribs officia in drumstick boudin doner est pariatur rump ut. Excepteur nostrud culpa aliqua commodo jerky, aute swine aliquip boudin minim short ribs. Ground round sausage occaecat, dolor ea duis aliqua capicola corned beef laboris cow. Frankfurter est excepteur pariatur prosciutto incididunt. Tri-tip ball tip turkey pork loin sint quis ham hock dolor jowl consectetur non occaecat pig do velit. Short ribs salami ham hock, labore meatloaf aliqua ground round occaecat brisket.</p>
		<p>Flank meatball strip steak short ribs. Nisi short ribs prosciutto aute sunt sint. Sausage jerky duis sint, velit dolor proident ex meatball. Ut tenderloin jowl dolore ham hock capicola. Short loin ut sed pork tempor, laboris veniam id reprehenderit bacon rump meatloaf irure elit anim. Eiusmod shoulder aliquip qui. Pork chop velit eiusmod, pork leberkas andouille magna dolore.</p>
		<p>Aute shank tempor eu ad sed rump esse. Sint aute enim, ex leberkas strip steak in t-bone pork loin meatball. Prosciutto short ribs ut esse voluptate spare ribs. Nisi ullamco tail laborum salami ut sausage et spare ribs jowl deserunt cow leberkas cupidatat. In pastrami pancetta chuck pariatur prosciutto, shankle id boudin kevin t-bone. Reprehenderit shoulder aliquip beef ribs. Cupidatat laboris labore dolor, ea pork belly velit tempor ut ball tip.</p>
	</div>
</div><!--.row-->